AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin specific exceptions
#
Layout/ExtraSpacing:
  Exclude:
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'data/new/**/*'
